# =============================================================================
# The concordance
# =============================================================================
#
# The same configuration carries a different name and a different default
# measurement in each package: relevent normalises, remstats counts, rem applies
# a mandatory (normalised) half-life decay and goldfish dichotomises. The table
# below is the review's cross-package concordance, restated in terms of the
# Revel call that reproduces each package's version. "Equivalent" means the same
# configuration AND the same measurement only where the call spells the
# measurement out.

const _CATALOGUE_COLUMNS = (:revel, :family, :configuration, :relevent, :remstats, :rem,
                            :goldfish, :eventnet, :source)

# revel call | family | configuration | relevent | remstats | rem | goldfish | eventnet | source
const _CATALOGUE = [
    # ---- the dyad and the reversed dyad --------------------------------------
    ("Inertia()", "endogenous", "past s → r events", "", "inertia()", "",
     "inertia(weighted = TRUE)", "DYAD_STATISTIC, dir OUT", "Brandes, Lerner & Snijders 2009"),
    ("Inertia(scaling=:prop, empty=1/(n-1))", "endogenous",
     "share of the sender's past sends that went to r", "FrPSndSnd",
     "inertia(scaling = \"prop\")", "", "", "", "Butts 2008; Kitts et al. 2017"),
    ("Inertia(transform=:indicator)", "endogenous", "has s ever sent to r", "", "", "",
     "inertia", "", "Stadtfeld & Block 2017"),
    ("Inertia(memory=HalfLife(h; normalized=true), weighted=true)", "endogenous",
     "half-life weighted s → r volume", "", "", "inertiaStat", "", "",
     "Brandes, Lerner & Snijders 2009"),
    ("Reciprocation()", "endogenous", "past r → s events", "", "reciprocity()", "",
     "recip(weighted = TRUE)", "DYAD_STATISTIC, dir IN", "Brandes, Lerner & Snijders 2009"),
    ("Reciprocation(scaling=:prop, empty=1/(n-1))", "endogenous",
     "share of the sender's past receipts that came from r", "FrRecSnd",
     "reciprocity(scaling = \"prop\")", "", "", "", "Butts 2008; Kitts et al. 2017"),
    ("Reciprocation(scaling=:prop, denominator=:receiver_out)", "endogenous",
     "share of the receiver's past sends that went to s", "", "", "", "", "",
     "Kitts et al. 2017"),
    ("Reciprocation(memory=HalfLife(h; normalized=true), weighted=true)", "endogenous",
     "half-life weighted r → s volume", "", "", "reciprocityStat", "", "",
     "Brandes, Lerner & Snijders 2009"),
    ("DyadActivity()", "endogenous", "past events between s and r, either way", "", "",
     "", "", "DYAD_STATISTIC, dir SYM", "Lerner & Lomi 2020"),
    # ---- node degree -----------------------------------------------------------
    ("OutdegreeSender()", "endogenous", "events sent by the sender", "",
     "outdegreeSender()", "degreeStat (sender-outdegree)", "outdeg(type = \"ego\")",
     "DEGREE_STATISTIC, OUT/SOURCE", "Vu et al. 2011"),
    ("OutdegreeSender(scaling=:prop, empty=1/(n-1))", "endogenous",
     "sender's share of all past sends", "NODSnd", "outdegreeSender(scaling = \"prop\")",
     "", "", "", "relevent"),
    ("IndegreeSender()", "endogenous", "events received by the sender", "",
     "indegreeSender()", "degreeStat (sender-indegree)", "indeg(type = \"ego\")", "",
     "Vu et al. 2011"),
    ("IndegreeSender(scaling=:prop, empty=1/(n-1))", "endogenous",
     "sender's share of all past receipts", "NIDSnd",
     "indegreeSender(scaling = \"prop\")", "", "", "", "relevent"),
    ("IndegreeReceiver()", "endogenous", "events received by the receiver", "",
     "indegreeReceiver()", "degreeStat (target-indegree)", "indeg(type = \"alter\")",
     "DEGREE_STATISTIC, IN/TARGET", "Vu et al. 2011"),
    ("IndegreeReceiver(scaling=:prop, empty=1/(n-1))", "endogenous",
     "receiver's share of all past receipts", "NIDRec",
     "indegreeReceiver(scaling = \"prop\")", "", "", "", "relevent"),
    ("OutdegreeReceiver()", "endogenous", "events sent by the receiver", "",
     "outdegreeReceiver()", "degreeStat (target-outdegree)", "outdeg(type = \"alter\")",
     "", "Vu et al. 2011"),
    ("OutdegreeReceiver(scaling=:prop, empty=1/(n-1))", "endogenous",
     "receiver's share of all past sends", "NODRec",
     "outdegreeReceiver(scaling = \"prop\")", "", "", "", "relevent"),
    ("TotaldegreeSender()", "endogenous", "events sent or received by the sender", "",
     "totaldegreeSender()", "", "", "degree statistic, SYM", "remstats"),
    ("TotaldegreeSender(scaling=:prop, empty=1/(n-1))", "endogenous",
     "sender's share of all past volume", "NTDegSnd",
     "totaldegreeSender(scaling = \"prop\")", "", "", "", "relevent"),
    ("TotaldegreeReceiver()", "endogenous", "events sent or received by the receiver",
     "", "totaldegreeReceiver()", "", "", "degree statistic, SYM", "remstats"),
    ("TotaldegreeReceiver(scaling=:prop, empty=1/(n-1))", "endogenous",
     "receiver's share of all past volume (preferential attachment)", "NTDegRec",
     "totaldegreeReceiver(scaling = \"prop\")", "", "", "", "Butts 2008"),
    ("OutdegreeSender(measure=:partners)", "endogenous",
     "distinct partners rather than events", "", "", "", "outdeg(weighted = FALSE)",
     "", "Vu, Lomi, Mascia & Pallotti 2017"),
    ("TotaldegreeDyad()", "endogenous", "sum of the two actors' total degrees", "",
     "totaldegreeDyad()", "", "", "", "remstats"),
    ("DegreeMin(symmetric=true)", "endogenous",
     "undirected: smaller of the two actors' event counts", "", "degreeMin()", "", "",
     "", "remstats"),
    ("DegreeMax(symmetric=true)", "endogenous",
     "undirected: larger of the two actors' event counts", "", "degreeMax()", "", "", "",
     "remstats"),
    ("DegreeDiff(symmetric=true)", "endogenous",
     "undirected: absolute difference of the two actors' event counts", "",
     "degreeDiff()", "", "", "", "remstats; Lerner, Hâncean & Perc 2025"),
    ("Inertia(symmetric=true)", "endogenous", "undirected: past events of the pair", "",
     "inertia() (undirected)", "", "inertia (choice_coordination)", "", "remstats"),
    ("DegreeAssortativity()", "endogenous", "sender out-degree × receiver in-degree",
     "", "outdegreeSender():indegreeReceiver()", "", "", "",
     "Vu, Lomi, Mascia & Pallotti 2017; Lerner & Lomi 2020"),
    # ---- the two-path ----------------------------------------------------------
    ("OTP()", "endogenous", "s → k → r, Σ min of the legs (transitive closure)",
     "OTPSnd", "otp()", "", "", "TRIANGLE_STATISTIC (\"transitive_tie\")", "Butts 2008"),
    ("OTP(combine=:count)", "endogenous", "number of distinct intermediaries", "",
     "otp(unique = TRUE)", "", "trans", "", "Stadtfeld & Block 2017"),
    ("OTP(combine=:product, root=true, memory=HalfLife(h; normalized=true))",
     "endogenous", "√ Σ products of half-life weights", "", "", "triadStat", "", "",
     "Brandes, Lerner & Snijders 2009"),
    ("OTP(combine=:product)", "endogenous", "Σ products of the legs", "", "", "", "", "",
     "Vu et al. 2011; Perry & Wolfe 2013 (\"2-send\")"),
    ("ITP()", "endogenous", "r → k → s (cyclic closure)", "ITPSnd", "itp()", "", "",
     "TRIANGLE_STATISTIC (\"cyclical_tie\")", "Butts 2008"),
    ("ITP(combine=:count)", "endogenous", "number of distinct intermediaries", "",
     "itp(unique = TRUE)", "", "cycle", "", "Stadtfeld & Block 2017"),
    ("OSP()", "endogenous", "s → k ← r (shared targets)", "OSPSnd", "osp()", "", "",
     "closure, both directions OUT", "Butts 2008"),
    ("OSP(combine=:count)", "endogenous", "number of shared targets", "",
     "osp(unique = TRUE)", "", "commonReceiver", "", "Stadtfeld & Block 2017"),
    ("ISP()", "endogenous", "s ← k → r (shared sources)", "ISPSnd", "isp()", "", "",
     "closure, both directions IN", "Butts 2008"),
    ("ISP(combine=:count)", "endogenous", "number of shared sources", "",
     "isp(unique = TRUE)", "", "commonSender", "", "Stadtfeld & Block 2017"),
    ("SharedPartners()", "endogenous", "undirected shared partners", "", "sp()", "",
     "trans (choice_coordination)", "closure, SYM", "remstats"),
    ("TwoPathEffect(layer_a, layer_b)", "endogenous",
     "two-path across two event networks or types", "",
     "consider_type = \"interact\"", "triadStat(eventtypevalues = )",
     "mixedTrans, mixedCycle, mixedCommonSender, mixedCommonReceiver",
     "different attributes per leg", "Stadtfeld & Block 2017"),
    ("BalanceEffect(:friend_of_friend)", "endogenous",
     "signed two-path on undirected ± weights (also :friend_of_enemy, " *
     ":enemy_of_friend, :enemy_of_enemy)", "", "", "triadStat(eventtypevalues = )", "",
     "\"enemy of friend\" closure", "Brandes, Lerner & Snijders 2009"),
    ("OTP(ordered=true)", "endogenous", "two-path whose first leg came first", "", "",
     "", "", "", "Arena, Mulder & Leenders 2022 (approximation)"),
    # ---- the three-path --------------------------------------------------------
    ("FourCycleEffect()", "endogenous", "s → a ← b → r, Σ min of three weights", "", "",
     "", "", "FOUR_CYCLE_STATISTIC", "Lerner & Lomi 2020"),
    ("FourCycleEffect(combine=:product, root=true, memory=HalfLife(h; normalized=true))",
     "endogenous", "cube root of Σ products", "", "", "fourCycleStat", "", "",
     "Brandenberger (rem)"),
    ("FourCycleEffect(combine=:count)", "endogenous", "number of three-paths", "", "",
     "", "four", "", "Stadtfeld & Block 2017; Haunss & Hollway 2023"),
    # ---- order-based devices ----------------------------------------------------
    ("RecencyRank(:receive)", "endogenous",
     "1/rank of r among those who most recently sent to s", "RRecSnd",
     "rrankReceive()", "", "", "", "Butts 2008"),
    ("RecencyRank(:send)", "endogenous",
     "1/rank of r among those s most recently sent to", "RSndSnd", "rrankSend()", "",
     "", "", "DuBois, Butts, McFarland & Smyth 2013"),
    ("TimeSince(:dyad)", "endogenous", "1/(time since the last s → r event + 1)", "",
     "recencyContinue()", "", "", "last-event-time attribute", "remstats"),
    ("TimeSince(:send_sender)", "endogenous", "1/(time since s last sent + 1)", "",
     "recencySendSender()", "", "", "", "remstats"),
    ("TimeSince(:send_receiver)", "endogenous", "1/(time since r last sent + 1)", "",
     "recencySendReceiver()", "", "", "", "remstats"),
    ("TimeSince(:receive_sender)", "endogenous", "1/(time since s last received + 1)",
     "", "recencyReceiveSender()", "", "", "", "remstats"),
    ("TimeSince(:receive_receiver)", "endogenous",
     "1/(time since r last received + 1)", "", "recencyReceiveReceiver()", "", "", "",
     "remstats"),
    ("TimeSince(:dyad; transform=identity)", "endogenous", "raw gap time", "", "", "",
     "", "", "Zappa & Vu 2021"),
    ("TimeSince(:pair)", "endogenous",
     "undirected: 1/(time since the pair last interacted + 1)", "",
     "recencyContinue() (undirected)", "", "", "", "remstats"),
    ("PShift(:AB_BA)", "endogenous",
     "participation shift (also :AB_BY, :AB_XA, :AB_XB, :AB_XY, :AB_AY and the seven " *
     "group-addressed shifts)", "PSAB-BA", "psABBA()", "", "", "", "Butts 2008"),
    ("PShiftABAB()", "endogenous", "the same dyad repeats immediately", "", "psABAB()",
     "", "", "", "remstats"),
    ("UndirectedPShift(:AB_AY)", "endogenous",
     "undirected: one actor of the last pair carries on with someone new (also :AB_AB)",
     "", "psABAY() (undirected)", "", "", "", "remstats"),
    # ---- neighbourhood statistics ------------------------------------------------
    ("NodeTransitivity()", "endogenous",
     "transitive structures in which the actor is the source", "", "", "", "nodeTrans",
     "", "Stadtfeld & Block 2017"),
    ("StructuralSimilarity()", "endogenous",
     "Jaccard / cosine similarity of the two actors' partner profiles", "", "", "", "",
     "JACCARD_SIM_STATISTIC, COSINE_SIM_STATISTIC", "eventnet"),
    # ---- exogenous -----------------------------------------------------------------
    ("SendEffect(x)", "exogenous", "sender's value", "CovSnd", "send()", "", "ego()",
     "NODE_STATISTIC, SOURCE", "Butts 2008"),
    ("ReceiveEffect(x)", "exogenous", "receiver's value", "CovRec", "receive()", "",
     "alter()", "NODE_STATISTIC, TARGET", "Butts 2008"),
    ("SumEffect(x)", "exogenous", "sender's plus receiver's value", "CovInt", "", "", "",
     "", "relevent"),
    ("AverageEffect(x)", "exogenous", "mean of the two values", "", "average()", "", "",
     "", "remstats"),
    ("MatchEffect(x)", "exogenous", "same category", "", "same()", "", "same()",
     "CATDIFF aggregation", "Perry & Wolfe 2013"),
    ("DiffEffect(x)", "exogenous", "absolute difference", "", "difference()", "",
     "diff()", "ABSDIFF aggregation", "remstats; goldfish"),
    ("SimEffect(x)", "exogenous", "negative absolute difference", "", "", "",
     "sim()", "", "goldfish"),
    ("MinimumEffect(x)", "exogenous", "smaller of the two values", "", "minimum()", "",
     "", "MIN aggregation", "remstats"),
    ("MaximumEffect(x)", "exogenous", "larger of the two values", "", "maximum()", "",
     "", "MAX aggregation", "remstats"),
    ("ProductEffect(x, y)", "exogenous", "sender's x × receiver's y", "",
     "send(\"x\"):receive(\"y\")", "", "egoAlterInt()", "PRODUCT aggregation",
     "Perry & Wolfe 2013"),
    ("TieEffect(matrix)", "exogenous", "dyadic covariate", "CovEvent", "tie()", "",
     "tie()", "DYAD_STATISTIC on an exogenous attribute", "Butts 2008"),
    ("GlobalEffect(f)", "exogenous", "covariate of time alone (a moderator)", "",
     "event()", "", "global attribute", "NETWORK_STATISTIC",
     "Lembo, Juozaitienė, Vinciotti & Wit 2025"),
    # ---- interactions --------------------------------------------------------------
    ("Interaction(a, b)", "interaction", "product term", "", "a:b", "", "", "", "remstats"),
    ("EventLayer(types=…); split_by_type", "interaction",
     "statistic split by the type of the past events", "",
     "consider_type = \"separate\"", "eventtypevar", "one network per type",
     "one attribute per event type", "Brandes, Lerner & Snijders 2009"),
    ("EventLayer(keep=…)", "interaction",
     "statistic on an attribute-filtered history", "", "", "eventfiltervar", "", "",
     "Brandenberger (rem)"),
    ("MatchedDegree(x)", "interaction",
     "degree over third actors who match the other endpoint on x", "", "",
     "degreeStat with filters", "", "*_NEIGHBOR_STAT",
     "Malang, Brandenberger & Leifeld 2019"),
    ("OTP(third=matching_third(x))", "interaction",
     "closure through third actors who match the sender on x", "", "",
     "triadStat(eventfilterAI = )", "", "closure with a node attribute", "rem; eventnet"),
    ("TertiusEffect(x)", "interaction",
     "aggregate of x over the receiver's in-neighbours", "", "", "", "tertius",
     "*_NEIGHBOR_STAT", "Stadtfeld & Block 2017; Haunss & Hollway 2023"),
    ("TertiusEffect(x; difference=true)", "interaction",
     "abs(sender's x − that aggregate): homophily at distance two", "", "", "",
     "tertiusDiff", "", "Haunss & Hollway 2023"),
    ("fit_stratified(…; by)", "interaction", "separate fits per stratum of events", "",
     "", "", "", "", "Amati, Lomi & Mascia 2019"),
    ("fit_moving_window(…; width)", "interaction", "time-varying coefficients", "",
     "remstimate::remwindow()", "", "", "", "Mulder & Leenders 2019"),
    ("Interaction(GlobalEffect(f), stat)", "interaction",
     "effect moderated by a period or a time of day", "", "", "", "",
     "network statistic interacted downstream", "Lembo et al. 2025"),
    # ---- hyperevents -----------------------------------------------------------------
    ("HyperedgeSize()", "hyperevent", "number of participants (a moderator only)", "",
     "", "", "", "UHE_SIZE_STAT, DHE_SIZE_STAT", "Lerner, Tranmer, Mowbray & Hâncean 2019"),
    ("ExactRepetition()", "hyperevent", "past events on exactly this hyperedge", "", "",
     "", "", "UHE_REPETITION_STAT, DHE_REPETITION_STAT",
     "Lerner, Tranmer, Mowbray & Hâncean 2019"),
    ("SubsetRepetition(p)", "hyperevent",
     "past events containing each p-subset of the participants, averaged", "", "", "",
     "", "UHE_SUB_REPETITION_STAT", "Lerner, Tranmer, Mowbray & Hâncean 2019"),
    ("SharedPriorEvents(p)", "hyperevent",
     "past events sharing at least p participants", "", "", "", "", "",
     "Lerner, Tranmer, Mowbray & Hâncean 2019"),
    ("PriorSuccess(p)", "hyperevent",
     "outcome-weighted over unweighted subset degree", "", "", "", "", "",
     "Lerner & Hâncean 2023"),
    ("DirectedSubsetRepetition(p, q)", "hyperevent",
     "past events containing p of the senders and q of the receivers", "", "", "", "",
     "DHE_SUB_REPETITION_STAT", "Lerner, Tranmer, Mowbray & Hâncean 2019"),
    ("UnorderedRepetition()", "hyperevent",
     "past events among the same actors in any roles (\"reply to all\")", "", "", "",
     "", "DHE_REPETITION_STAT, dir SYM", "Lerner & Lomi 2023"),
    ("ReceiverSetRepetition(p)", "hyperevent",
     "partial receiver-set repetition of order p", "", "", "", "",
     "DHE_SUB_REPETITION_STAT, endpoint TARGET", "Lerner & Lomi 2023"),
    ("SenderReceiverSetRepetition(p)", "hyperevent",
     "sender-specific partial receiver-set repetition", "", "", "", "",
     "DHE_SUB_REPETITION_STAT", "Lerner & Lomi 2023"),
    ("HyperSenderActivity()", "hyperevent", "past events sent by the senders", "", "",
     "", "", "DHE_SUB_REPETITION_STAT (1, 0)", "Lerner & Lomi 2023"),
    ("HyperReceiverPopularity()", "hyperevent", "past events received by the receivers",
     "", "", "", "", "DHE_SUB_REPETITION_STAT (0, 1)", "Lerner & Lomi 2023"),
    ("HyperReciprocation()", "hyperevent",
     "past events from the receivers to the sender", "", "", "", "",
     "DHE_SUB_REPETITION_STAT, dir IN", "Lerner & Lomi 2023"),
    ("OutInPopularity()", "hyperevent", "past events sent by the receivers", "", "", "",
     "", "", "Lerner & Lomi 2023"),
    ("InteractionAmongReceivers(p)", "hyperevent",
     "past interaction among the receivers", "", "", "", "", "", "Lerner & Lomi 2023"),
    ("HyperClosure()", "hyperevent",
     "two-path closure on the dyadic projection, over the hyperedge's pairs", "", "", "",
     "", "UHE_CLOSURE_STAT, DHE_CLOSURE_STAT",
     "Lerner, Lomi, Mowbray, Rollings & Tranmer 2021"),
    ("HyperCovariate(x)", "hyperevent",
     "summary of an actor covariate over the hyperedge", "", "", "", "",
     "UHE_NODE_STAT, DHE_NODE_STAT", "Lerner & Lomi 2023"),
    # ---- measurement choices -------------------------------------------------------
    ("memory=HalfLife(h)", "memory", "exponential decay", "",
     "memory = \"decay\"", "halflife (normalized=true)", "", "attribute half-life",
     "Brandes, Lerner & Snijders 2009"),
    ("memory=Window(w)", "memory", "sliding window", "", "memory = \"window\"", "",
     "window", "", "de Nooy 2011; Quintane et al. 2013"),
    ("memory=Interval(a, b)", "memory", "one interval of the past", "",
     "memory = \"interval\"", "", "", "", "Perry & Wolfe 2013"),
    ("memory=PowerLaw(α)", "memory", "power-law decay", "", "", "", "", "",
     "Vu, Lomi, Mascia & Pallotti 2017"),
    ("memory=LinearDecay(span)", "memory", "linear decay", "", "", "", "", "",
     "Arena, Mulder & Leenders 2023"),
    ("clock=:order", "memory", "age measured in events", "", "", "", "", "",
     "Malang, Brandenberger & Leifeld 2019"),
    ("weighted=true", "memory", "event weights instead of counts", "",
     "weight column", "weight", "weighted = TRUE", "event weight response",
     "Brandes, Lerner & Snijders 2009"),
    ("Standardized(stat, n; corrected=true)", "scaling", "z-score across the risk set",
     "", "scaling = \"std\"", "", "", "", "remstats"),
    ("transform=:log1p", "scaling", "log(1 + x)", "", "", "", "transformFun",
     "LOG1P function", "Fritz, Rastelli, Fop & Caimo 2025"),
]

"""
    effect_catalogue() -> DataFrame

The concordance between Revel's effects and the vocabulary of the other
relational-event packages: one row per effect with the `revel` call, its
`family` (`endogenous`, `exogenous`, `interaction`, `hyperevent`, `memory`,
`scaling`), the
`configuration` it measures, the name under which `relevent`, `remstats`, `rem`,
`goldfish` and `eventnet` offer it (empty when a package does not), and the
`source` that proposed it.

The same name does not mean the same number across packages — they differ in
scaling, in the zero-history value, in how the legs of a two-path are combined
and in the normalisation of the decay kernel — so each `revel` entry spells out
the options that reproduce the other package's measurement. The remstats column
is pinned against remstats 4.1.0 by a golden fixture and the relevent column
against Relevent.jl's relevent-validated statistics; the rem, goldfish and
eventnet columns follow those packages' documentation. One remstats difference
is deliberate: under `memory = "decay"` remstats evaluates the decay at the
*previous* event's time, Revel at the time of the event being explained.

# Example
```julia
using Revel
cat = effect_catalogue()
names(cat)[1:4]                                   # ["revel", "family", "configuration", "relevent"]
cat[cat.relevent .== "FrPSndSnd", :revel]         # ["Inertia(scaling=:prop, empty=1/(n-1))"]
cat[cat.goldfish .== "commonReceiver", :revel]    # ["OSP(combine=:count)"]
```
"""
function effect_catalogue()
    cols = [String[row[k] for row in _CATALOGUE] for k in eachindex(_CATALOGUE_COLUMNS)]
    return DataFrame(cols, collect(_CATALOGUE_COLUMNS))
end
